-- Script d'exemple PostgreSQL : schéma et données initiales du POC Chat.
-- Il n'est pas exécuté automatiquement par Docker Compose ni par Spring Boot.

CREATE TABLE IF NOT EXISTS agencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS client_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL REFERENCES agencies(id),
    guest_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id),
    sender_type VARCHAR(255) NOT NULL CHECK (sender_type IN ('CUSTOMER', 'AGENCY')),
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_conversations_agency_id ON conversations(agency_id);
CREATE INDEX IF NOT EXISTS idx_conversations_agency_guest_status
    ON conversations(agency_id, guest_id, status);
CREATE INDEX IF NOT EXISTS idx_conversations_guest_status_created_at
    ON conversations(guest_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
    ON messages(conversation_id, created_at);

INSERT INTO agencies (code, name)
VALUES
    ('AG-001', 'Agence Paris Center'),
    ('AG-002', 'Agence Lyon Sud'),
    ('AG-003', 'Agence Marseille Port')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO client_accounts (username, display_name, password)
VALUES
    ('client1', 'Client 1', 'mot de passe client'),
    ('client2', 'Client 2', 'mot de passe client')
ON CONFLICT (username) DO UPDATE
SET display_name = EXCLUDED.display_name,
    password = EXCLUDED.password;